# update_fastlane
fastlane_version "1.98.0"

default_platform :ios
ENV["GYM_USE_LEGACY_BUILD_API"] = "true"

platform :ios do
    before_all do
#       carthage ( platform: "iOS" )
#       cocoapods
    end
    
    desc "Runs all the tests"
    lane :test do
        xctest(
            scheme: "",
            destination: "platform=iOS Simulator,name=iPhone 6,OS=9.3",
        )
    end
    
    desc "Build"
    lane :build do
       gym(scheme: "AsciiArt") 
    end
    
    desc "Build for AdHoc"
    lane :adhoc do
        sigh(
            adhoc: true

        )
        ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
        gym(
            workspace: "AsciiArt.xcworkspace",
            clean: true,
            configuration: "Release",
            scheme: 'AsciiArt',
            silent: true,
            output_name: "AsciiArtAdHoc.ipa", 
            export_method: "ad-hoc"
        )
    end

    after_all do |lane|
    end

    error do |lane, exception|
    end
end
